# Set the language
language: node_js

# Set the Node version
node_js:
  - '10'

services:
  # Use Docker command line
  - docker

install:
  # Install dependencies
  - npm ci

script:
  # Run server
  - npm start

after_script:
  # Stop server
  - npm stop  